// Generated by nitro
import type { Serialize, Simplify } from "nitropack/types";
declare module "nitropack/types" {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/api/agency-cms/auth/login': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/agency-cms/auth/login.post').default>>>>
    }
    '/api/agency-cms/auth/logout': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/agency-cms/auth/logout.post').default>>>>
    }
    '/api/agency-cms/auth/me': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/agency-cms/auth/me.get').default>>>>
    }
    '/api/agency-cms/auth/setup': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/agency-cms/auth/setup.post').default>>>>
    }
    '/api/agency-cms/cms/about-content': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/agency-cms/cms/about-content.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/agency-cms/cms/about-content.post').default>>>>
    }
    '/api/agency-cms/cms/contact-content': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/agency-cms/cms/contact-content.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/agency-cms/cms/contact-content.post').default>>>>
    }
    '/api/agency-cms/cms/faqs': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/agency-cms/cms/faqs.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/agency-cms/cms/faqs.post').default>>>>
    }
    '/api/agency-cms/cms/faqs/:id': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/agency-cms/cms/faqs/[id].delete').default>>>>
      'put': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/agency-cms/cms/faqs/[id].put').default>>>>
    }
    '/api/agency-cms/cms/home-content': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/agency-cms/cms/home-content.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/agency-cms/cms/home-content.post').default>>>>
    }
    '/api/agency-cms/cms/services-content': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/agency-cms/cms/services-content.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/agency-cms/cms/services-content.post').default>>>>
    }
    '/api/agency-cms/cms/services': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/agency-cms/cms/services.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/agency-cms/cms/services.post').default>>>>
    }
    '/api/agency-cms/cms/services/:id': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/agency-cms/cms/services/[id].delete').default>>>>
      'put': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/agency-cms/cms/services/[id].put').default>>>>
    }
    '/api/agency-cms/cms/site-settings': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/agency-cms/cms/site-settings.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/agency-cms/cms/site-settings.post').default>>>>
    }
    '/api/agency-cms/cms/team-content': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/agency-cms/cms/team-content.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/agency-cms/cms/team-content.post').default>>>>
    }
    '/api/agency-cms/cms/team': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/agency-cms/cms/team.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/agency-cms/cms/team.post').default>>>>
    }
    '/api/agency-cms/cms/team/:id': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/agency-cms/cms/team/[id].delete').default>>>>
      'put': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/agency-cms/cms/team/[id].put').default>>>>
    }
    '/api/agency-cms/upload/image': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/agency-cms/upload/image.post').default>>>>
    }
    '/api/local-spot/auth/login': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/local-spot/auth/login.post').default>>>>
    }
    '/api/local-spot/auth/me': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/local-spot/auth/me.get').default>>>>
    }
    '/api/local-spot/auth/register': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/local-spot/auth/register.post').default>>>>
    }
    '/api/local-spot/auth/seed': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/local-spot/auth/seed.post').default>>>>
    }
    '/api/local-spot/docs': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/local-spot/docs/index.get').default>>>>
    }
    '/api/local-spot/permissions/:id': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/local-spot/permissions/[id].delete').default>>>>
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/local-spot/permissions/[id].get').default>>>>
      'put': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/local-spot/permissions/[id].put').default>>>>
    }
    '/api/local-spot/permissions': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/local-spot/permissions/index.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/local-spot/permissions/index.post').default>>>>
    }
    '/api/local-spot/permissions/migrate': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/local-spot/permissions/migrate.post').default>>>>
    }
    '/api/local-spot/permissions/modules': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/local-spot/permissions/modules.get').default>>>>
    }
    '/api/local-spot/permissions/seed': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/local-spot/permissions/seed.post').default>>>>
    }
    '/api/local-spot/permissions/status': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/local-spot/permissions/status.get').default>>>>
    }
    '/api/local-spot/roles/:id': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/local-spot/roles/[id].delete').default>>>>
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/local-spot/roles/[id].get').default>>>>
      'put': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/local-spot/roles/[id].put').default>>>>
    }
    '/api/local-spot/roles': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/local-spot/roles/index.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/local-spot/roles/index.post').default>>>>
    }
    '/api/local-spot/roles/seed': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/local-spot/roles/seed.post').default>>>>
    }
    '/api/local-spot/users/:id': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/local-spot/users/[id].delete').default>>>>
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/local-spot/users/[id].get').default>>>>
      'put': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/local-spot/users/[id].put').default>>>>
    }
    '/api/local-spot/users/:id/roles': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/local-spot/users/[id]/roles.get').default>>>>
      'put': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/local-spot/users/[id]/roles.put').default>>>>
    }
    '/api/local-spot/users': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/local-spot/users/index.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/local-spot/users/index.post').default>>>>
    }
    '/__nuxt_error': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/nuxt/dist/core/runtime/nitro/handlers/renderer').default>>>>
    }
    '/__nuxt_island/**': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/#internal/nuxt/island-renderer').default>>>>
    }
  }
}
export {}