// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 9/23/2025, 8:34:22 PM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
import cfg3 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["/Users/phurachanphowutthirat/repositories/claude/web_monorepo/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/phurachanphowutthirat/repositories/claude/web_monorepo/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/phurachanphowutthirat/repositories/claude/web_monorepo/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/phurachanphowutthirat/repositories/claude/web_monorepo/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/phurachanphowutthirat/repositories/claude/web_monorepo/plugins/**/*.{js,ts,mjs}","/Users/phurachanphowutthirat/repositories/claude/web_monorepo/composables/**/*.{js,ts,mjs}","/Users/phurachanphowutthirat/repositories/claude/web_monorepo/utils/**/*.{js,ts,mjs}","/Users/phurachanphowutthirat/repositories/claude/web_monorepo/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/phurachanphowutthirat/repositories/claude/web_monorepo/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/phurachanphowutthirat/repositories/claude/web_monorepo/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/phurachanphowutthirat/repositories/claude/web_monorepo/app.config.{js,ts,mjs}"]}},
{},
cfg2,
cfg3,
{"content":{"files":["/Users/phurachanphowutthirat/repositories/claude/digital-agency/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/phurachanphowutthirat/repositories/claude/digital-agency/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/phurachanphowutthirat/repositories/claude/digital-agency/plugins/**/*.{js,ts,mjs}","/Users/phurachanphowutthirat/repositories/claude/digital-agency/composables/**/*.{js,ts,mjs}","/Users/phurachanphowutthirat/repositories/claude/digital-agency/utils/**/*.{js,ts,mjs}","/Users/phurachanphowutthirat/repositories/claude/digital-agency/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/phurachanphowutthirat/repositories/claude/digital-agency/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/phurachanphowutthirat/repositories/claude/digital-agency/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/phurachanphowutthirat/repositories/claude/digital-agency/app.config.{js,ts,mjs}","/Users/phurachanphowutthirat/repositories/claude/digital-agency/app/spa-loading-template.html"]}}
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;